services:
  investment-journey-calc:
    container_name: investment-journey-calc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped
